version: '3.4'

services:
  worker:
    build: .
    command: celery -B -A tasx worker --loglevel INFO
    environment:
      REDIS_HOST: redis
      RABBIT_HOST: rabbitmq
    env_file: .env
    depends_on:
      - rabbitmq
      - redis

  rabbitmq:
    image: rabbitmq:3.7
    ports:
      - 15672:15672

  redis:
    image: redis:alpine
    ports:
      - 6379:6379